EXCHANGE_API_KEY = "e676c38802d148d5b012b8a473a6dee1"
API_HTTP = "https://openexchangerates.org/api/latest.json"

# SET False IF YOU DONT HAVE AN INTERNET CONNECTION
# EXCHANGE OPTION WILL BE UNAVALIABLE
EXCHANGE_IS_ACTIVE = True