# Generated by Django 3.2.6 on 2021-08-26 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='RUB', max_length=20)),
                ('balance', models.CharField(max_length=1000000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=1000000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_app.client')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_app.wallet')),
            ],
        ),
    ]
