# Generated by Django 3.2.6 on 2021-08-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0002_auto_20210827_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
