# Generated by Django 3.2.6 on 2021-08-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0003_operation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_deposite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_client', models.IntegerField(default=None)),
                ('description', models.CharField(max_length=200)),
                ('balance_changing', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=None)),
                ('currency', models.CharField(default='RUB', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operation_draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_client', models.IntegerField(default=None)),
                ('description', models.CharField(max_length=200)),
                ('balance_changing', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=None)),
                ('currency', models.CharField(default='RUB', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avito_app.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
