# Generated by Django 3.2.6 on 2021-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0004_auto_20210827_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation_deposite',
            old_name='from_client',
            new_name='second_client',
        ),
        migrations.AddField(
            model_name='operation_deposite',
            name='operation_type',
            field=models.CharField(choices=[('depo', 'deposite'), ('draw', 'draw')], default=None, max_length=4),
        ),
        migrations.DeleteModel(
            name='Operation_draw',
        ),
    ]
