# Generated by Django 3.2.6 on 2021-08-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0005_auto_20210827_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operation_deposite',
            new_name='Operation',
        ),
    ]
