# Generated by Django 3.2.6 on 2021-08-29 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0006_rename_operation_deposite_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='client',
        ),
        migrations.AddField(
            model_name='operation',
            name='client_from',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='avito_app.client'),
        ),
        migrations.AddField(
            model_name='operation',
            name='client_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='avito_app.client'),
        ),
    ]
