# Generated by Django 3.2.6 on 2021-08-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0007_auto_20210829_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='second_client',
        ),
    ]
