# Generated by Django 3.2.6 on 2021-08-29 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0009_remove_operation_operation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='date',
        ),
    ]
