# Generated by Django 3.2.6 on 2021-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito_app', '0013_rename_bankoperations_bankoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankoperation',
            name='RUB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bankoperation',
            name='currency',
            field=models.CharField(default='RUB', max_length=4),
        ),
    ]
